title: Personal Page
theme: minima
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I have a big dream which is to earn twenty million ¥ before 30 years old!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Poisson-SHAN # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
